name: 'setup-env'
description: 'Setup BrowserStack Test Environment'
inputs:
  username:
    description: 'BrowserStack Username'
    required: true
  access-key:
    description: 'BrowserStack Access Key'
    required: true
  build-name:
    description: 'Build name for the tests'
    required: false
  project-name:
    description: 'Project name for the tests'
    required: false
  rerun-attempt:
    description: 'ReRun attempt'
    required: false
    default: 'none'
  repository:
    description: 'GitHub context - Repository'
    required: false
    default: 'none'
  run-id:
    description: 'GitHub context - Run_ID'
    required: false
    default: 'none'
  github-token:
    description: 'GitHub Token for authentication'
    required: false
    default: 'none'
  github-app:
    description: 'BrowserStack Github App'
    required: false
    default: 'bstack-gha-app[bot]'
runs:
  using: 'node20'
  main: 'dist/index.js'
