name: 'setup-rerun-vars'
description: 'Setup BrowserStack Rerun Variables'

inputs:
  run_attempt:
    description: 'Run attempt number'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check if this is a re-run
      shell: bash
      run: |
        if [ "${{ inputs.run_attempt }}" -gt 1 ]; then
          echo "This run is a re-run (attempt #${{ inputs.run_attempt }})."
        else
          echo "This is the first run."
        fi

