name: 'setup-rerun-vars'
description: 'Setup BrowserStack Rerun Variables'

inputs:
  run_attempt:
    description: 'Run attempt number'
    required: true
  github_context:
    description: 'GitHub context as a JSON string'
    required: true
  github_token:
    description: 'GitHub Token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check if this is a re-run
      shell: bash
      run: |
        # Parse the JSON string input
        github_context=$(echo "${{ inputs.github_context }}" | jq -r '.')
        run_id=$(echo "$github_context" | jq -r '.run_id')
        repository=$(echo "$github_context" | jq -r '.repository')

        if [ "${{ inputs.run_attempt }}" -gt 1 ]; then
          echo "This run is a re-run (attempt #${{ inputs.run_attempt }})."
          curl -H "Authorization: token ${{ inputs.github_token }}" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/$repository/actions/runs/$run_id" > run_details.json
          triggering_actor=$(jq -r '.triggering_actor.login' run_details.json)
          echo "Triggering Actor: $triggering_actor"
          if [[ "$triggering_actor" == "gha-bstack-rerun[bot]" ]]; then
            echo "The run was triggered by the GitHub App."
          else
            echo "The run was triggered by: ${{ github.actor }}"
          fi
        else
          echo "This is the first run."
        fi
