name: 'setup-rerun-vars'
description: 'Setup BrowserStack Rerun Variables'

inputs:
  repository:
    description: 'GitHub context - Repository'
    required: true
  run_id:
    description: 'GitHub context - Run_ID'
    required: true
  github_token:
    description: 'GitHub Token for authentication'
    required: true


runs:
  using: 'composite'
  steps:
    - name: Set environment variables required for re-run, to be used by SDK
      shell: bash
      run: |
        # Assign inputs to variables
        run_id="${{ inputs.run_id }}"
        repository="${{ inputs.repository }}"
        github_token="${{ inputs.github_token }}"
        
        # Get the triggering actor
        curl -H "Authorization: token $github_token" \
             -H "Accept: application/vnd.github.v3+json" \
             "https://api.github.com/repos/$repository/actions/runs/$run_id" > run_details.json
        triggering_actor=$(jq -r '.triggering_actor.login' run_details.json)
        echo "Triggering Actor: $triggering_actor"
        
        # Check if BrowserStack has triggered the re-run
        if [[ "$triggering_actor" == "bstack-trigger[bot]" ]]; then
          echo "The run was triggered by the GitHub App."

          # TODO - Call BrowserStack API to get the values of the 2 environment values
          
          # Set the environment variables
          echo "BSTACK_IS_RERUN=true" >> $GITHUB_ENV
          echo "BSTACK_RERUN_TESTS=test1" >> $GITHUB_ENV
        fi

