name: 'setup-rerun-vars'
description: 'Setup BrowserStack Rerun Variables'

inputs:
  run_attempt:
    description: 'Run attempt number'
    required: true
  repository:
    description: 'GitHub context - Repository'
    required: true
  run_id:
    description: 'GitHub context - Run_ID'
    required: true
  github_token:
    description: 'GitHub Token'
    required: true

outputs:
  tests_to_run:
    description: 'Modified tests to run based on rerun logic'

runs:
  using: 'composite'
  steps:
    - name: Check if this is a re-run
      shell: bash
      run: |
        # Assign inputs to variables
        run_id="${{ inputs.run_id }}"
        repository="${{ inputs.repository }}"
        github_token="${{ inputs.github_token }}"
        run_attempt="${{ inputs.run_attempt }}"

        if [ "$run_attempt" -gt 1 ]; then
          echo "This run is a re-run (attempt #${run_attempt})."
          curl -H "Authorization: token $github_token" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/$repository/actions/runs/$run_id" > run_details.json
          triggering_actor=$(jq -r '.triggering_actor.login' run_details.json)
          echo "Triggering Actor: $triggering_actor"
          if [[ "$triggering_actor" == "gha-bstack-rerun[bot]" ]]; then
            echo "The run was triggered by the GitHub App."
            echo "::set-output name=tests_to_run::rerun_tests"
          else
            echo "The run was triggered by: ${{ github.actor }}"
            echo "::set-output name=tests_to_run::all_tests"
          fi
        else
          echo "This is the first run."
          echo "::set-output name=tests_to_run::all_tests"
        fi
