name: 'setup-rerun-vars'
description: 'Setup BrowserStack Rerun Variables'

jobs:
  check-rerun:
    runs-on: ubuntu-latest
    steps:
      - name: Check if this is a re-run
        run: |
          if [ "${{ github.run_attempt }}" -gt 1 ]; then
            echo "This run is a re-run (attempt #${{ github.run_attempt }})."
          else
            echo "This is the first run."
          fi
